version: '3'
services:
  nfl-draft-manager:
    image: lfallo1/nfldraftmanager:latest
    environment:
      - SPRING_PROFILES_ACTIVE
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
    ports:
      - "8080:8080"
  nfl-draft-importer:
    image: lfallo1/nfldraftimporter:latest
    environment:
      - SPRING_PROFILES_ACTIVE
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
    ports:
      - "9000:9000"
  nfl-draft-messagequeue:
    image: rabbitmq:3-management
    hostname: "nfl-draft-messagequeue"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    ports:
      - "15672:15672"